using System.Security.Cryptography;
using System.Text;

namespace VRChatSDKInspectorJPLocalization.Core;

public static class PoDocument
{
    private const string FormatLine = "# Block-Format: 1";
    private const string VersionPrefix = "# Translation-Version: ";
    private const string PaddingPrefix = "# Added-LF: ";
    private const string HashPrefix = "# Content-SHA256: ";

    /// <summary>専用ブロックの位置と完全性の検査</summary>
    public static InstallationInfo Inspect(string text)
    {
        var begins = FindAll(text, AppConstants.BeginMarker);
        var ends = FindAll(text, AppConstants.EndMarker);
        if (begins.Count == 0 && ends.Count == 0)
            return new(InstallationState.NotInstalled, "未インストール");
        if (begins.Count != 1 || ends.Count != 1 || begins[0] >= ends[0])
            return new(InstallationState.Abnormal, "専用マーカーの欠落・重複・順序異常があります。");
        var start = begins[0];
        var end = ends[0] + AppConstants.EndMarker.Length;
        if ((start > 0 && text[start - 1] != '\n') || end >= text.Length || text[end] != '\n')
            return new(InstallationState.Abnormal, "専用マーカーの行形式が不正です。");
        end++;
        var block = text[start..end];
        var lines = block.Split('\n');
        if (lines.Length < 9 || lines[1] != FormatLine || !lines[2].StartsWith(VersionPrefix, StringComparison.Ordinal) ||
            !lines[3].StartsWith(PaddingPrefix, StringComparison.Ordinal) || !lines[4].StartsWith(HashPrefix, StringComparison.Ordinal) || lines[5] != "")
            return new(InstallationState.Abnormal, "専用ブロックの形式が未対応または破損しています。");
        var version = lines[2][VersionPrefix.Length..];
        var paddingText = lines[3][PaddingPrefix.Length..];
        if (version.Length == 0 || paddingText is not ("0" or "1" or "2"))
            return new(InstallationState.Abnormal, "専用ブロックのメタデータが不正です。");
        var padding = paddingText[0] - '0';
        if (start < padding || text[(start - padding)..start] != new string('\n', padding))
            return new(InstallationState.Abnormal, "専用ブロック直前の区切りが変更されています。");
        var original = text[..(start - padding)];
        if (RequiredPadding(original) != padding)
            return new(InstallationState.Abnormal, "専用ブロックの改行情報が一致しません。");
        var payloadStart = lines.Take(6).Sum(line => line.Length + 1);
        var payload = block[payloadStart..(block.Length - AppConstants.EndMarker.Length - 1)];
        if (Hash(version + "\n" + paddingText + "\n" + payload) != lines[4][HashPrefix.Length..])
            return new(InstallationState.Abnormal, "専用ブロック内が変更されています。自動で削除・修復しません。");
        try { PoSyntax.ReadMessageIds(payload); }
        catch (InvalidDataException ex) { return new(InstallationState.Abnormal, ex.Message); }
        return new(InstallationState.Installed, "インストール済み", start - padding, end - start + padding, version);
    }

    /// <summary>重複を除いた専用ブロックの生成と追記</summary>
    public static string Install(string text, IReadOnlyList<Translation> translations, string translationVersion)
    {
        if (string.IsNullOrWhiteSpace(translationVersion) || translationVersion.Any(char.IsControl))
            throw new InvalidDataException("翻訳データの識別子が不正です。");
        var info = Inspect(text);
        if (info.State != InstallationState.NotInstalled)
            throw new InvalidDataException("未インストールの正常なファイルにのみインストールできます。" + info.Message);
        var existing = PoSyntax.ReadMessageIds(text);
        if (existing.Count == 0) throw new InvalidDataException("既存POエントリがありません。");
        var payload = new StringBuilder("# Generated by " + AppConstants.AppName + "\n\n");
        var inputIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var translation in translations)
        {
            if (string.IsNullOrWhiteSpace(translation.English) || string.IsNullOrWhiteSpace(translation.Japanese) || !inputIds.Add(translation.English))
                throw new InvalidDataException("翻訳データに空欄または重複があります。");
            if (existing.Contains(translation.English)) continue;
            payload.Append("msgid ").Append(PoSyntax.Quote(translation.English)).Append('\n')
                .Append("msgstr ").Append(PoSyntax.Quote(translation.Japanese)).Append("\n\n");
        }
        var padding = RequiredPadding(text);
        var result = text + new string('\n', padding) + AppConstants.BeginMarker + "\n" + FormatLine + "\n"
            + VersionPrefix + translationVersion + "\n" + PaddingPrefix + padding + "\n"
            + HashPrefix + Hash(translationVersion + "\n" + padding + "\n" + payload) + "\n\n" + payload + AppConstants.EndMarker + "\n";
        if (Inspect(result).State != InstallationState.Installed)
            throw new InvalidDataException("生成した専用ブロックの検証に失敗しました。");
        PoSyntax.ReadMessageIds(result);
        return result;
    }

    /// <summary>検証済みの専用ブロックと追加した区切り改行のみの削除</summary>
    public static string Uninstall(string text)
    {
        var info = Inspect(text);
        if (info.State != InstallationState.Installed)
            throw new InvalidDataException("正常にインストールされたブロックがありません。" + info.Message);
        return text.Remove(info.Start, info.Length);
    }

    /// <summary>指定操作によるPO文書の更新</summary>
    public static string Transform(string text, TranslationOperation operation, IReadOnlyList<Translation> translations, string translationVersion)
    {
        PoSyntax.ReadMessageIds(text);
        var result = operation switch
        {
            TranslationOperation.Install => Install(text, translations, translationVersion),
            TranslationOperation.Reinstall => Install(Uninstall(text), translations, translationVersion),
            TranslationOperation.Uninstall => Uninstall(text),
            _ => throw new ArgumentOutOfRangeException(nameof(operation))
        };
        PoSyntax.ReadMessageIds(result);
        return result;
    }

    /// <summary>既存末尾を変更しない区切り改行数の計算</summary>
    private static int RequiredPadding(string text) => text.Length == 0 || text.EndsWith("\n\n", StringComparison.Ordinal)
        ? 0 : text.EndsWith('\n') ? 1 : 2;

    /// <summary>内容のSHA256の生成</summary>
    private static string Hash(string text) => Convert.ToHexString(SHA256.HashData(Utf8Document.Encoding.GetBytes(text)));

    /// <summary>マーカーの全出現位置の収集</summary>
    private static List<int> FindAll(string text, string marker)
    {
        var result = new List<int>();
        var offset = 0;
        while ((offset = text.IndexOf(marker, offset, StringComparison.Ordinal)) >= 0)
        {
            result.Add(offset);
            offset += marker.Length;
        }
        return result;
    }
}
